[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "hello"
crate-type = ["staticlib"]
path = "src/hello"

[profile.release]
lto = "off"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
